✨ : se agrega código base sin pruebas
PilarMassL/gg-scaffolding-lambda-go pull request #2
Opened 2022-01-08 20:30 UTC by alejandro56664-adl

- Se agrega código base para acceder a un almacén de archivos remoto basado en S3.

2022-01-19 21:00 UTC, ricardo-vargas-adl requested changes
se ve chevere el código pero podemos hacer esas mejoras que vi.

2022-01-19 21:00 UTC, ricardo-vargas-adl commented on prototype/project-name/function-name/adapter/MyStorageUsingS3.go
> +	_, err := uploader.Upload(context.TODO(), &s3.PutObjectInput{
@alejandro56664-adl validemos de que forma podemos pasarle el contexto que recibe el handler.

2022-01-19 21:00 UTC, ricardo-vargas-adl commented on prototype/project-name/function-name/adapter/MyStorageUsingS3.go
> +	headObject, errHeadObject := s.awsS3Client.HeadObject(context.TODO(), &s3.HeadObjectInput{
Igual aqui el handler maneja un contexto es decir que lo puede recibir por parametro.

2022-01-19 21:00 UTC, ricardo-vargas-adl commented on prototype/project-name/function-name/adapter/MyStorageUsingS3.go
> +	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion(AWS_S3_REGION))
Hace poco aprendí que no es necesario definir esto en constantes las lambdas por defecto traen dos variables de entorno con la region en la que se esta desplegando la lambda. 

Esto es código python pero podemos definir que se lean del environment.
    region1 = os.environ['AWS_REGION']
    region2 = os.environ['AWS_DEFAULT_REGION']

2022-01-19 21:00 UTC, ricardo-vargas-adl commented on prototype/project-name/function-name/cmd/lambda/main.go
> +	//lambda.Start(myHttpHandler.Handler)
Pilas con dejar estos códigos comentareados.

2022-01-20 17:24 UTC, alejandro56664-adl commented on prototype/project-name/function-name/adapter/MyStorageUsingS3.go
> +	headObject, errHeadObject := s.awsS3Client.HeadObject(context.TODO(), &s3.HeadObjectInput{
Para no acoplar la interfaz con el contexto, se crea como campo del objeto que implementa la interfaz.

2022-01-20 17:24 UTC, alejandro56664-adl commented on prototype/project-name/function-name/adapter/MyStorageUsingS3.go
> +	_, err := uploader.Upload(context.TODO(), &s3.PutObjectInput{
Para no acoplar la interfaz con el contexto, se crea como campo del objeto que implementa la interfaz.

2022-01-20 17:25 UTC, jamoralesva commented on prototype/project-name/function-name/cmd/lambda/main.go
> +	//lambda.Start(myHttpHandler.Handler)
Se agrega el adapter al servicio raíz de la función. Lo único que cambia es el handler que se inyecta en el lambda Start.

2022-01-21 20:45 UTC, merged